services:
  socket-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socket-server
    ports:
      - "3001:3001"
    environment:
      - SOCKET_PORT=3001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7.0-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge